services:
  basic-statistics:
    container_name: basic-statistics
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/jovyan/work:delegated
    ports:
      - 8888:8888
    env_file:
      - .env
    command: 'start-notebook.sh --NotebookApp.token='
